services:
  db:
    container_name: tradein_chevrolet_db
    image: postgres:17
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres11
      POSTGRES_DB: tradein

    volumes:
      - tradein_pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: tradein_chevrolet_pgadmin
    image: dpage/pgadmin4:7.1
    ports:
      - "5050:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  bot:
    container_name: tradein_chevrolet_bot
    build: .

    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}

    volumes:
      - tradein_uploads:/app/uploads

volumes:
  tradein_pgdata:
  tradein_uploads:
